import { z } from "zod"

export const trackEventSchema = z.object({
  eventName: z.enum([
    "PAGE_VIEW",
    "PRODUCT_VIEW",
    "CATEGORY_VIEW",
    "SEARCH",
    "FILTER_CHANGE",
    "SORT_CHANGE",
    "SIZE_SELECTED",
    "COLOR_SELECTED",
    "ADD_TO_CART",
    "REMOVE_FROM_CART",
    "START_CHECKOUT",
    "PAYMENT_SUCCESS",
    "PAYMENT_FAILED",
    "LOGIN",
    "REGISTER",
    "NEWSLETTER_SUBSCRIBE",
    "WISHLIST_ADD",
    "WISHLIST_REMOVE",
    "RECOMMENDATION_CLICK",
  ]),
  correlationId: z.string().optional(),
  version: z.number().int().default(1),
  page: z.string().optional(),
  path: z.string().optional(),
  productId: z.string().uuid().optional(),
  categoryId: z.string().uuid().optional(),
  collectionId: z.string().uuid().optional(),
  device: z.string().optional(),
  browser: z.string().optional(),
  os: z.string().optional(),
  country: z.string().optional(),
  language: z.string().optional(),
  currency: z.string().optional(),
  utmSource: z.string().optional(),
  utmMedium: z.string().optional(),
  utmCampaign: z.string().optional(),
  referrer: z.string().optional(),
  metadata: z.record(z.string(), z.any()).optional(),
})

export const searchRecordSchema = z.object({
  query: z.string().min(1, "Query string required"),
  resultsCount: z.number().int().default(0),
  clickedProductId: z.string().uuid().optional(),
  converted: z.boolean().default(false),
})
